=== elbereth/DragonUnPACKer/tags/release-57010/DragonUnPACKer/tools/duhtcomp/templates/xml-db/dup5-xml-db.dtd
<!ELEMENT dup5db (head,entries,extrainfo)>
<!ELEMENT head (filename,format,directory,dupver,dupedit,dupurl)>
<!ELEMENT entries (entry*)>
<!ELEMENT entry (file,file0,fileext,directory,desc,offset,size)>
<!ELEMENT filename (#PCDATA)>
<!ELEMENT format (#PCDATA)>
<!ELEMENT directory (#PCDATA)>
<!ELEMENT dupver (#PCDATA)>
<!ELEMENT dupedit (#PCDATA)>
<!ELEMENT dupurl (#PCDATA)>
<!ELEMENT file (#PCDATA)>
<!ELEMENT file0 (#PCDATA)>
<!ELEMENT fileext (#PCDATA)>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT offset (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT extrainfo (totalbytes,totalentries)>
<!ELEMENT totalbytes (#PCDATA)>
<!ELEMENT totalentries (#PCDATA)>

=== elbereth/DragonUnPACKer/trunk/DragonUnPACKer/tools/duhtcomp/teamplates/xml/header.xml
<?xml version="1.0"?>
<!DOCTYPE dup5db SYSTEM "dup5-xml-db.dtd">
<dup5db>
  <head>
    <filename>$$FILENAME$$</filename>
    <format>$$FORMAT$$</format>
    <directory>$$DIRECTORY$$</directory>
    <dupver>$$DUPVER$$</dupver>
    <dupedit>$$DUPEDIT$$</dupedit>
    <dupurl>$$DUPURL$$</dupurl>
  </head>
  <entries>
